import {MainNav} from '@/components/ui/main-nav'
import {MainHeader} from '@/components/ui/main-header'
import {Inter} from 'next/font/google'
import {Metadata} from 'next'
import '../globals.css'
import {Toaster} from '@/components/ui/toaster'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-stone-50 min-h-screen`}>
        <nav className='ml-2 px-5 pt-4'>
          <MainHeader />
        </nav>
        <div className='sticky top-0 bg-white border-b px-5 shadow-md'>
          <MainNav />
        </div>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
