import {Button} from '@/components/ui/button'
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {MainNav} from '@/components/ui/main-nav'
import {MainHeader} from '@/components/ui/main-header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className=''>
          <div className=''>
            <nav className='ml-2 px-5 pt-4'>
              <MainHeader />
            </nav>
            <div className='sticky top-0 bg-white border-b px-5 shadow-md'>
              <MainNav />
            </div>
            <div className=''>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
// <div className='absolute w-full bottom-0 left-1/2 transform -translate-x-1/2 h-1 border-b-2 border-black'></div>
